export const actionType = {
  FETCH_ARTIST_DATA_SUCCESS: "FETCH_ARTIST_DATA_SUCCESS",
  FETCH_ARTIST_DATA_FAILURE: "FETCH_ARTIST_DATA_FAILURE",
  FETCH_ARTIST_DATA_RESET: "FETCH_ARTIST_DATA_RESET",
  FETCH_ARTIST_DATA_LOADING: "FETCH_ARTIST_DATA_LOADING",
  SORT_ARTIST_DATA: "SORT_ARTIST_DATA",
  POST_NEW_ARTIST_SUCCESS: "POST_NEW_ARTIST_SUCCESS",
  POST_NEW_ARTIST_FAILURE: "POST_NEW_ARTIST_FAILURE",
  POST_NEW_ARTIST_RESET: "POST_NEW_ARTIST_RESET",
  POST_NEW_ARTIST_LOADING: "POST_NEW_ARTIST_LOADING",
};
