export const actionType = {
  FETCH_ARTIST_DATA_SUCCESS: "FETCH_ARTIST_DATA_SUCCESS",
  FETCH_ARTIST_DATA_FAILURE: "FETCH_ARTIST_DATA_FAILURE",
  FETCH_ARTIST_DATA_RESET: "FETCH_ARTIST_DATA_RESET",
  FETCH_ARTIST_DATA_LOADING: "FETCH_ARTIST_DATA_LOADING",
};
