export const actionType = {
  FETCH_SONG_DATA_SUCCESS: "FETCH_SONG_DATA_SUCCESS",
  FETCH_SONG_DATA_FAILURE: "FETCH_SONG_DATA_FAILURE",
  FETCH_SONG_DATA_RESET: "FETCH_SONG_DATA_RESET",
  FETCH_SONG_DATA_LOADING: "FETCH_SONG_DATA_LOADING",
};
