export const actionType = {
  FETCH_SONG_DATA_SUCCESS: "FETCH_SONG_DATA_SUCCESS",
  FETCH_SONG_DATA_FAILURE: "FETCH_SONG_DATA_FAILURE",
  FETCH_SONG_DATA_RESET: "FETCH_SONG_DATA_RESET",
  FETCH_SONG_DATA_LOADING: "FETCH_SONG_DATA_LOADING",
  SORT_SONG_DATA: "SORT_SONG_DATA",
  POST_NEW_SONG_SUCCESS: "POST_NEW_SONG_SUCCESS",
  POST_NEW_SONG_FAILURE: "POST_NEW_SONG_FAILURE",
  POST_NEW_SONG_RESET: "POST_NEW_SONG_RESET",
  POST_NEW_SONG_LOADING: "POST_NEW_SONG_LOADING",
};
