export const actionType = {
  FETCH_USER_DATA_SUCCESS: "FETCH_USER_DATA_SUCCESS",
  FETCH_USER_DATA_FAILURE: "FETCH_USER_DATA_FAILURE",
  FETCH_USER_DATA_RESET: "FETCH_USER_DATA_RESET",
  FETCH_USER_DATA_LOADING: "FETCH_USER_DATA_LOADING",
};
